
project_id = "kcbvdcacgbwigefwacrk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "auth"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true

[storage]
enabled = true

[realtime]
enabled = true

[functions.historical-data-request]
verify_jwt = true
