version: '3.8'

services:
  # Frontend React application
  frontend:
    container_name: meu-residencial-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - NPM_CONFIG_UPDATE_NOTIFIER=false
      - NPM_CONFIG_FUND=false
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend-node-modules: 